### ISSUE TITLE
Is it working at all?

### ISSUE THREAD

**Issue by wielgi** [breejesh/DigitalWatermark#1] opened 2018-07-12 11:46 UTC
It seemed to work well but then I tested it on images that are completly different and it still had like 65% success of reading watermark...

**Comment by breejesh** [comment] 2018-07-12 12:36
Hey

Can you send me the images you used? That way I'll be able to debug it
better. Yes it definitely works. I had documented it with results. It was a
PoC I had made within a day so didn't have time for extensive testing.

**Comment by wielgi** [comment] 2018-07-12 13:31
Ok so I tested it a bit more and it seems that its working only on images that dont have big areas of the same color. So landscapes are good but I tried to use it on products images. They are shot on white background and product itself is mainly one color. 
The problem is at generating owner's share. So its the way algorithm is working. I dont think it can be used to protect images from stealing.

If you compare two images that are similar (have dark and light areas in similar places) you still will extract watermark from "stolen image" even its completly different object on it.

**Comment by breejesh** [comment] 2018-07-12 13:48
Kindly do not conclude things. If you are not getting ideal results, share the images you used so that I can point out and help.  I don't think a watermark will be regenerated from a completely random image if it's complex enough. I understand your point (from what I read) and a workaround should be to change the pseudorandom points if they are similar. Or rather, not to select points in a random manner but implement an algorithm which selects points with different gray levels.

**Comment by wielgi** [comment] 2018-07-12 14:13
Those are random images I tested it on. 
* http://babydesign.eu/wp-content/uploads/2017/04/zdjecie-w-galerii-6.jpg
* https://mocnerowery.pl/imgcache/b87d98ecb7cab743cc0c594ec7440b96/Bateria_1200x800.jpg

I picked them because them both have, a white background and dark object in the middle.

First image was my "original_image". I run "python owernership_share_generator.py" to generate master_img and owner_img from it. I used same watermark as in your example.
Second image was my "stolen_image_0". I run python master_share_generator.py and python watermark_generator.py on it.

Thats how my regenerated watermark is looking:
![watermark_img_0](https://user-images.githubusercontent.com/22418939/42638194-4b9733b4-85ed-11e8-9e75-e9f93ceafac0.jpg)

**Comment by breejesh** [comment] 2018-07-12 14:45
Okay, the issue is as suspected. Selection of points to be used. The inverse of ownership share generated is almost the watermark itself. This can be solved if a point selection algorithm is implemented which ensures that the inverse of ownership share is not similar to the watermark. If you can do that by yourself, well and good. As I mentioned already this was just a PoC which was not extensively tested and there can be caveats like the one you found. For now, I will just close this stating that **This will not work on images with large patches of the same color**. If I get time, I will implement the fix myself. Thanks!

**Comment by breejesh** [comment] 2018-07-12 14:45
Okay, the issue is as suspected. Selection of points to be used. The inverse of ownership share generated is almost the watermark itself. This can be solved if a point selection algorithm is implemented which ensures that the inverse of ownership share is not similar to the watermark. If you can do that by yourself, well and good. As I mentioned already this was just a PoC which was not extensively tested and there can be caveats like the one you found. For now, I will just close this stating that **This will not work on images with large patches of the same color**. If I get time, I will implement the fix myself. Thanks!

**Closed as completed by breejesh** 2018-07-12 14:45 UTC
